### ISSUE TITLE
Possible (minor) memory leak

### ISSUE THREAD

**Issue by sixten** [Objective3/ElementParser#2]
Running the XCode 3.2 static analyzer on my project, and thus also on ElementParser, it pointed out that the method `parseElementAttributesWithRange:caseSensative:` in NSString_HTML.m allocates the array attributes, and then returns it with a retain count of one. Is that intentional behavior (that the caller of this method becomes the owner of the array), or should that method be autoreleasing the array (as would be usual)?

**Comment by parisman** [comment]
no. this is a bug. will be fixed shortly
