### ISSUE TITLE
One more static analysis item

### ISSUE THREAD

**Issue by sixten** [Objective3/ElementParser#3]
In the method `parseHTML:delegate:selector:context:index:partial:` (in NSString_HTML.m), you might want to set a default value for the local var `len`. Clang was able to find a path through the method where it doesn't get a value before it's passed to `NSMakeRange()` on line 458. Looks like it works like this:
- At the top of the main while loop (line 371), `c` gets the ampersand.
- The variable `len` is allocated on line 374.
- Execution will fall through to the else if on line 430.
- If `interior` is zero, `partialChunk` is set, but not `len` (lines 432-7).
- It should be the case that `len` then gets initialized on line 450, but if the conditional on line 446 is true, execution won't reach that line. (Or if, for whatever reason, `partialChunk` ended up nil on line 444).

Now, whether this is likely to actually happen, I couldn't say. I suspect you might be able to craft an input document that would do this, though. At any rate, take it for what it's worth. :-)

**Comment by parisman** [comment]
nice detective work. I'll add the initializer although I am not convinced that it can actually occur.

**Comment by sixten** [comment]
Well, that definitely happens with static analysis bugs: the compiler doesn't know anything about usage.

**Comment by parisman** [comment]
best to keep the compiler happy!
BTW, any feedback on ElementParser? Useful? 
Have you/would you recommend?
